SELECT A.VDPRDPRD_CODR AS 'COD. PROD', A.VDPRDPRD_DESCRI AS 'DESCRIÇÃO',  

CASE 

    WHEN A.VDPRDPRD_PERMITE_BONIF = 1 THEN 'SIM'
    WHEN A.VDPRDPRD_PERMITE_BONIF = 0 THEN 'NÃO' END AS 'BONIF. MANUAL',


CASE 

   WHEN A.VDPRDPRD_PERMITE_BONIF_SFA = 1 THEN 'SIM'
   WHEN A.VDPRDPRD_PERMITE_BONIF_SFA = 0 THEN 'NÃO' END AS 'BONIF. SFA',

CASE

    WHEN A.VDPRDPRD_FLAG = 'A' THEN 'ATIVO'
    WHEN A.VDPRDPRD_FLAG = 'I' THEN 'INATIVO' END AS 'STATUS'


FROM CADPRD01 AS A