--Juntando as colunas de Regiao e Sequencia do Cliente e adicioanando Zeros.

SELECT CAST(VDCLICLI_REGI AS VARCHAR(300)) || REPEAT('0',4-LENGTH(CAST(VDCLICLI_NUM AS VARCHAR(300)))) || CAST(VDCLICLI_NUM AS VARCHAR(300)) FROM CADCLI01

--Contando os dias aparti de uma data

DAYS_BETWEEN(CAST(LEFT(CAST(A.CRMOVMOV_DTV AS VARCHAR(300)),4) || SUBSTRING(CAST(A.CRMOVMOV_DTV AS VARCHAR(300)),5,2) || RIGHT(CAST(A.CRMOVMOV_DTV AS VARCHAR(300)),2) AS DATE),CURDATE()) AS DIAS

--Convertendo data Americana/SQL/Control para Data BR

CAST(RIGHT(CAST(A.CRMOVMOV_DTE AS VARCHAR(300)),2) || '/' || SUBSTRING(CAST(A.CRMOVMOV_DTE AS VARCHAR(300)),5,2) || '/' || LEFT(CAST(A.CRMOVMOV_DTE AS VARCHAR(300)),4) AS VARCHAR(300)) AS 'DATA EMISSAO'

--Conversão do CURDATE() para Data BR

CAST(SUBSTRING(CAST(CURDATE() AS VARCHAR(300)),9,2) || '/' || SUBSTRING(CAST(CURDATE() AS VARCHAR(300)),6,2) || '/' || SUBSTRING(CAST(CURDATE() AS VARCHAR(300)),1,4) AS VARCHAR(300))

--Calculando Juros apartir dos dias
--Metodo usado (Taxa do Juros 6% /mes divido por 30 ficando 0,002 por dia)

(DAYS_BETWEEN(CAST(LEFT(CAST(A.CRMOVMOV_DTV AS VARCHAR(300)),4) || SUBSTRING(CAST(A.CRMOVMOV_DTV AS VARCHAR(300)),5,2) || RIGHT(CAST(A.CRMOVMOV_DTV AS VARCHAR(300)),2) AS DATE),CURDATE()) * 0.002 * A.CRMOVMOV_VALOR) AS JUROS

--Metodo do Uso do CASE

CASE 

     WHEN(A.VDPEDCPE_TPCOBR)  >= 4 THEN 'PRAZO'  
      WHEN(A.VDPEDCPE_TPCOBR)  = 1 THEN 'A VISTA' END AS 'PRAZO', CAST(A.VDPEDCPE_CPG AS VARCHAR(300)) || ' - ' || CAST(E.VDCADPAG_DESCR AS VARCHAR(300)) AS 'COND. PG',

CASE 

    WHEN(F.VDPEDIPE_OCOKD) >= 1 THEN 'VENDA'
    WHEN(F.VDPEDIPE_OCOKD) >= 2 THEN 'BONIFICAÇÃO'
    WHEN(F.VDPEDIPE_OCOKD) >= 1 AND F.VDPEDIPE_OCOKD <= 2 THEN 'VENDA/BONI' END AS 'TIPO'


--CALCULANDO O DIA ENTRE DUAS DATAS - STARTDATE & ENDDATE

SELECT DAYS_BETWEEN(CAST(LEFT(CAST(CRMOVMOV_DTV AS VARCHAR(300)),4) || SUBSTRING(CAST(CRMOVMOV_DTV AS VARCHAR(300)),5,2) || RIGHT(CAST(CRMOVMOV_DTV AS VARCHAR(300)),2) AS DATE), CURDATE()) AS DIAS FROM CADMOV01 LIMIT 10