SELECT DISTINCT A.VDPEDIPE_CODCLI AS 'COD. CLI',

SUM(
CASE
      WHEN A.VDPEDIPE_CODR = 901133 THEN A.VDPEDIPE_QTDPRD
   END) AS '901133',

SUM(
   CASE
      WHEN A.VDPEDIPE_CODR = 902311 THEN A.VDPEDIPE_QTDPRD
   END) AS '902311',

SUM(
   CASE
      WHEN A.VDPEDIPE_CODR = 903061 THEN A.VDPEDIPE_QTDPRD
   END) AS '903061',

SUM(
   CASE
      WHEN A.VDPEDIPE_CODR = 903129 THEN A.VDPEDIPE_QTDPRD
   END) AS '903129',

SUM(
   CASE
      WHEN A.VDPEDIPE_CODR = 902402 THEN A.VDPEDIPE_QTDPRD
   END) AS '902402',

SUM(
   CASE
      WHEN A.VDPEDIPE_CODR = 904213 THEN A.VDPEDIPE_QTDPRD
   END) AS '904213',

SUM(
   CASE
      WHEN A.VDPEDIPE_CODR = 903129 THEN A.VDPEDIPE_QTDPRD
   END) AS '903129'

FROM PEDIT01 AS A

YEAR(MONTH(CAST(SUBSTRING(CAST(A.VDPEDIPE_NIT AS VARCHAR(300)),1,4) || SUBSTRING(CAST(A.VDPEDIPE_NIT AS VARCHAR(300)),5,2) || SUBSTRING(CAST(A.VDPEDIPE_NIT AS VARCHAR(300)),7,2) AS DATE))) = YEAR(MONTH(CURDATE()))

GROUP BY A.VDPEDIPE_CODCLI, A.VDPEDIPE_CODR, A.VDPEDIPE_QTDPRD
