SELECT A.VDCEVPEN_CODCLI AS 'COD.CLIENTE', A.VDCEVPEN_PROD AS 'PRODUTO', A.VDCEVPEN_DTV AS 'VALIDADE', COUNT(A.VDCEVPEN_NPED) AS 'QUANTIDADE', 

CASE
    WHEN A.VDCEVPEN_PROD = 471 THEN A.VDCEVPEN_QTDPRD_ORI
    WHEN A.VDCEVPEN_PROD = 2496 THEN A.VDCEVPEN_QTDPRD_ORI
END AS '600ML'


FROM CEVPED01 AS A
INNER JOIN CADCLI01 AS B ON CAST(A.VDCEVPEN_CODCLI AS VARCHAR(300))=CAST(VDCLICLI_REGI AS VARCHAR(300)) || REPEAT('0',4-LENGTH(CAST(VDCLICLI_NUM AS VARCHAR(300)))) || CAST(VDCLICLI_NUM AS VARCHAR(300))
INNER JOIN PEDCP01 AS C ON A.VDCEVPEN_CODCLI=C.VDPEDCPE_CODCLI

WHERE CAST(LEFT(CAST(VDPEDCPE_NPED AS VARCHAR(300)),4) || SUBSTRING(CAST(VDPEDCPE_NPED AS VARCHAR(300)),5,2) || SUBSTRING(CAST(VDPEDCPE_NPED AS VARCHAR(300)),7,2) AS DATE) = CURDATE()

GROUP BY A.VDCEVPEN_CODCLI, A.VDCEVPEN_PROD, A.VDCEVPEN_DTV, A.VDCEVPEN_NPED