Select CAST(A.VDCLICLI_REGI AS VARCHAR(300)) || REPEAT('0',4-LENGTH(CAST(A.VDCLICLI_NUM AS VARCHAR(300)))) || CAST(A.VDCLICLI_NUM AS VARCHAR(300)) as 'Cod. Cliente', A.VDCLICLI_SIGLA AS 'NOME FANTASIA', A.VDCLICLI_RAZAO50 AS 'RAZÃO SOCIAL', A.VDCLICLI_VEN AS 'VENDEDOR', B.VDCLICLI_SUPVD AS 'SUPERVISOR', A.VDCLICLI_CODPASTA1 AS 'PASTA',

CASE 

    WHEN A.VDCLICLI_CODPASTA1 = 9999 AND A.VDCLICLI_VEN = 999  THEN 'INATIVO'
    WHEN A.VDCLICLI_CODPASTA1 != 9999 AND A.VDCLICLI_VEN != 999  THEN 'ATIVO'

END AS 'STATUS',

A.VDCLICLI_CREDITO AS 'LIMITE CREDITO', A.VDCLICLI_CONTATO AS 'CONTATO', A.VDCLICLI_FONE AS 'TELEFONE 1',

A.VDCLICLI_FONE2 AS 'TELEFONE 2'


From CADCLI01 AS A
INNER JOIN CADVEN01 AS B ON A.VDCLICLI_VEN=B.VDVENVEN_SUPVD