SELECT A.CRMOVMOV_NDUPL AS 'NUM. TITULO', A.CRMOVMOV_CCLI AS 'COD. CLIENTE', 

CASE
    WHEN B.VDPEDIPE_OCOKD = 1
    B.VDPEDIPE_OCOKD = 006 
    OR
    B.VDPEDIPE_OCOKD = 007 
    OR
    B.VDPEDIPE_OCOKD = 009 
    OR
    B.VDPEDIPE_OCOKD = 014 
    OR
    B.VDPEDIPE_OCOKD = 017 
    OR
    B.VDPEDIPE_OCOKD = 019 
    OR
    B.VDPEDIPE_OCOKD = 024 
    OR
    B.VDPEDIPE_OCOKD = 026 
    OR
    B.VDPEDIPE_OCOKD = 029 
    OR
    B.VDPEDIPE_OCOKD = 032 
    OR
    B.VDPEDIPE_OCOKD = 033 
    OR
    B.VDPEDIPE_OCOKD = 035 
    OR
    B.VDPEDIPE_OCOKD = 036 
    OR
    B.VDPEDIPE_OCOKD = 052 
    OR
    B.VDPEDIPE_OCOKD = 071 
    OR
    B.VDPEDIPE_OCOKD = 082 
    OR
    B.VDPEDIPE_OCOKD = 083 
    OR
    B.VDPEDIPE_OCOKD = 101 
    OR
    B.VDPEDIPE_OCOKD = 140 
    OR
    B.VDPEDIPE_OCOKD = 141 
    OR
    B.VDPEDIPE_OCOKD = 170 
    OR
    B.VDPEDIPE_OCOKD = 588 
    OR
    B.VDPEDIPE_OCOKD = 901 
    OR
    B.VDPEDIPE_OCOKD = 904 
    OR
    B.VDPEDIPE_OCOKD = 905 
    OR
    B.VDPEDIPE_OCOKD = 906 
    OR
    B.VDPEDIPE_OCOKD = 907 
    OR
    B.VDPEDIPE_OCOKD = 914 
    OR
    B.VDPEDIPE_OCOKD = 915 
    OR
    B.VDPEDIPE_OCOKD = 918 
    OR
    B.VDPEDIPE_OCOKD = 920 
    OR
    B.VDPEDIPE_OCOKD = 921 
    OR
    B.VDPEDIPE_OCOKD = 927 
    OR
    B.VDPEDIPE_OCOKD = 928 
    OR
    B.VDPEDIPE_OCOKD = 929 
    OR
    B.VDPEDIPE_OCOKD = 948 
    OR
    B.VDPEDIPE_OCOKD = 949 
    OR
    B.VDPEDIPE_OCOKD = 950 
    OR
    B.VDPEDIPE_OCOKD = 951 
    OR
    B.VDPEDIPE_OCOKD = 953 
    OR
    B.VDPEDIPE_OCOKD = 954 
    OR
    B.VDPEDIPE_OCOKD = 955 
    OR
    B.VDPEDIPE_OCOKD = 956 
    OR
    B.VDPEDIPE_OCOKD = 963 
        
     THEN  B.VDPEDIPE_PREPRDT  END
    
    AS 'VLR. ORIGINAL'

FROM CADMOV01 AS A
INNER JOIN PEDIT01 AS B ON A.CRMOVMOV_NPED=B.VDPEDIPE_NIT

WHERE A.CRMOVMOV_CCLI = 240338