SELECT A.CRMOVMOV_NDUPL AS 'NUM. TITULO', A.CRMOVMOV_CCLI AS 'COD. CLIENTE',

CASE 
    WHEN C.VDPEDIPE_OCOKD <> 2 THEN C.VDPEDIPE_PREPRDU * C.VDPEDIPE_QTDPRD
END AS 'VLR. ORIGINAL'

FROM CADMOV01 AS A
INNER JOIN PEDCP01 AS B ON A.CRMOVMOV_NPED=B.VDPEDCPE_NPED
INNER JOIN PEDIT01 AS C ON A.CRMOVMOV_NPED=C.VDPEDIPE_NIT

WHERE B.VDPEDCPE_FL = 8 AND B.VDPEDCPE_MOTDEV < '01'

GROUP BY A.CRMOVMOV_NDUPL, C.VDPEDIPE_OCOKD, C.VDPEDIPE_PREPRDT, B.VDPEDCPE_VLR_FCEM, A.CRMOVMOV_CCLI, C.VDPEDIPE_QTDPRD, C.VDPEDIPE_PREPRDU 