SELECT A.CRMOVMOV_NDUPL AS 'NUM. TITULO', A.CRMOVMOV_CCLI AS 'COD. CLIENTE', 

CASE 
   WHEN B.VDPEDIPE_OCOKD = 1 

     THEN  B.VDPEDIPE_PREPRDT END
    AS 'VLR. ORIGINAL'

FROM CADMOV01 AS A
INNER JOIN PEDIT01 AS B ON A.CRMOVMOV_NPED=B.VDPEDIPE_NIT
INNER JOIN PEDCP01 AS C ON A.CRMOVMOV_NPED=C.VDPEDCPE_NPED

--CODIGO CORRIGIDO