SELECT 
 CAST(LEFT(CAST(B.VDPEDCPE_DTEMIPED AS VARCHAR(300)),4) || SUBSTRING(CAST(B.VDPEDCPE_DTEMIPED AS VARCHAR(300)),5,2) || RIGHT(CAST(B.VDPEDCPE_DTEMIPED AS VARCHAR(300)),2) AS DATE) AS 'DATA DE EMISSÃO', C.VDPRDPRD_DESCR AS 'DESCRIÇÃO',

SUM(A.VDPEDIPE_QTDPRD) AS 'CX VERDE'


FROM PEDIT01 AS A
INNER JOIN PEDCP01 AS B ON A.VDPEDIPE_NIT=B.VDPEDCPE_NPED
INNER JOIN CADPRD01 AS C ON A.VDPEDIPE_CODR=C.VDPRDPRD_CODR

WHERE  B.VDPEDCPE_FL = 8 AND A.VDPEDIPE_CODR=215442 AND B.VDPEDCPE_MOTDEV < '01'

GROUP BY A.VDPEDIPE_CODR, B.VDPEDCPE_DTEMIPED, A.VDPEDIPE_QTDPRD, C.VDPRDPRD_DESCR