SELECT CAST(VDCLICLI_REGI AS VARCHAR(300)) || REPEAT('0',4-LENGTH(CAST(VDCLICLI_NUM AS VARCHAR(300)))) || CAST(VDCLICLI_NUM AS VARCHAR(300)) AS 'COD. CLIENTE', A.VDCLICLI_SIGLA AS 'NOME FANTASIA', A.VDCLICLI_RAZAO50 AS 'RAZÃO SOCIAL', A.VDCLICLI_CGC AS 'CNPJ', A.VDCLICLI_FONE AS 'TELEFONE', A.VDCLICLI_VEN AS 'VD', B.VDVENVEN_SUPVD AS 'SUP', CAST(A.VDCLICLI_CPG AS VARCHAR(300)) || ' - ' || CAST(C.VDCADPAG_DESCR AS VARCHAR(300)) AS 'COND. PG'



 FROM CADCLI01 AS A 
INNER JOIN CADVEN01 AS B ON A.VDCLICLI_VEN=B.VDVENVEN_CODMOV
INNER JOIN CONDPG01 AS C ON A.VDCLICLI_CPG=C.VDCADPAG_COD

WHERE A.VDCLICLI_VEN < '900'