SELECT 

A.CRMOVMOV_CCLI AS 'COD.CLIENTE',  

A.CRMOVMOV_VALOR AS 'VALOR', 

CAST(RIGHT(CAST(A.CRMOVMOV_DTE AS VARCHAR(300)),2) || '/' || SUBSTRING(CAST(A.CRMOVMOV_DTE AS VARCHAR(300)),5,2) || '/' || LEFT(CAST(A.CRMOVMOV_DTE AS VARCHAR(300)),4) AS VARCHAR(300)) AS 'DATA EMISSAO',

CAST(RIGHT(CAST(A.CRMOVMOV_DTV AS VARCHAR(300)),2) || '/' || SUBSTRING(CAST(A.CRMOVMOV_DTV AS VARCHAR(300)),5,2) || '/' || LEFT(CAST(A.CRMOVMOV_DTV AS VARCHAR(300)),4) AS VARCHAR(300)) AS 'DATA VENCIMENTO'

FROM CADMOV01 AS A
