SELECT DISTINCT A.VDPEDCPE_CODCLI AS 'COD CLI', A.VDPEDCPE_NPED AS 'NUM PED', SUM(B.VDPEDIPE_PREPRDT) AS 'VLR TOTAL', CAST(LEFT(CAST(A.VDPEDCPE_DTEMIPED AS VARCHAR(300)),4) || SUBSTRING(CAST(A.VDPEDCPE_DTEMIPED AS VARCHAR(300)),5,2) || RIGHT(CAST(A.VDPEDCPE_DTEMIPED AS VARCHAR(300)),2) AS DATE) AS 'DATA DE EMISSAO'

FROM PEDCP01 AS A
INNER JOIN PEDIT01 AS B ON B.VDPEDIPE_NIT=A.VDPEDCPE_NPED

WHERE CAST(LEFT(CAST(VDPEDCPE_NPED AS VARCHAR(300)),4) || SUBSTRING(CAST(VDPEDCPE_NPED AS VARCHAR(300)),5,2) || SUBSTRING(CAST(VDPEDCPE_NPED AS VARCHAR(300)),7,2) AS DATE) >= ADD_DAYS(CURDATE(),-DAYS_BETWEEN(CURDATE(),ADD_MONTHS(CURDATE(),-3))) AND A.VDPEDCPE_FL = 8 AND A.VDPEDCPE_MOTDEV < '01' AND B.VDPEDIPE_OCOKD = 1

GROUP BY A.VDPEDCPE_CODCLI, A.VDPEDCPE_NPED, B.VDPEDIPE_PREPRDT, A.VDPEDCPE_DTEMIPED