SELECT 

A.CRMOVMOV_CCLI AS 'COD.CLIENTE',  

A.CRMOVMOV_VALOR AS 'VALOR', 

CAST(RIGHT(CAST(A.CRMOVMOV_DTE AS VARCHAR(300)),2) || '/' || SUBSTRING(CAST(A.CRMOVMOV_DTE AS VARCHAR(300)),5,2) || '/' || LEFT(CAST(A.CRMOVMOV_DTE AS VARCHAR(300)),4) AS VARCHAR(300)) AS 'DATA EMISSAO',

CAST(RIGHT(CAST(A.CRMOVMOV_DTV AS VARCHAR(300)),2) || '/' || SUBSTRING(CAST(A.CRMOVMOV_DTV AS VARCHAR(300)),5,2) || '/' || LEFT(CAST(A.CRMOVMOV_DTV AS VARCHAR(300)),4) AS VARCHAR(300)) AS 'DATA VENCIMENTO'

FROM CADMOV01 AS A
INNER JOIN PEDCP01 AS B ON A.CRMOVMOV_CCLI=B.VDPEDCPE_CODCLI

WHERE CAST(LEFT(CAST(CRMOVMOV_DTE AS VARCHAR(300)),4) || SUBSTRING(CAST(CRMOVMOV_DTE AS VARCHAR(300)),5,2) || SUBSTRING(CAST(CRMOVMOV_DTE AS VARCHAR(300)),7,2) AS DATE) >= ADD_DAYS(CURDATE(),-DAYS_BETWEEN(CURDATE(),ADD_MONTHS(CURDATE(),-3)))