SELECT CAST(VDCLICLI_REGI AS VARCHAR(300)) || REPEAT('0',4-LENGTH(CAST(VDCLICLI_NUM AS VARCHAR(300)))) || CAST(VDCLICLI_NUM AS VARCHAR(300)) AS 'COD. CLIENTE', A.VDCLICLI_CREDITO AS 'VLR. CREDITO', A.VDCLICLI_DEBITO AS 'VLR. USADO'

FROM CADCLI01 AS A