SELECT VDNOPOCO_COD AS 'OCORRENCIA', VDNOPOCO_NOME AS 'DESCRIÇÃO',

CASE 
WHEN VDNOPOCO_INATIVO_FAT = 1 THEN 'INATIVO' 
WHEN VDNOPOCO_INATIVO_FAT = 0 THEN 'ATIVO'  END
AS 'STATUS FAT.', 

CASE
WHEN VDNOPOCO_OCOPALM = 0 THEN 'NÃO DISPON. PALM'
WHEN VDNOPOCO_OCOPALM = 1 THEN 'DISPON. PALM' END

 AS 'STATUS PALM' 

FROM CADOCO01 AS A
INNER JOIN PEDIT01 AS B ON A.VDNOPOCO_COD=B.VDPEDIPE_OCOKD
INNER JOIN PEDCP01 AS C ON B.VDPEDIPE_NIT=C.VDPEDCPE_NPED

WHERE MONTH(CAST(LEFT(CAST(VDPEDIPE_NIT AS VARCHAR(300)),4) ||  SUBSTRING(CAST(A.VDPEDIPE_NIT AS VARCHAR(300)),5,2) || SUBSTRING(CAST(VDPEDIPE_NIT AS VARCHAR(300)),7,2) AS DATE)) = MONTH(CURDATE()) AND B.VDPEDCPE_FL = 8 AND B.VDPEDCPE_MOTDEV < '01' AND YEAR(CAST(LEFT(CAST(VDPEDIPE_NIT AS VARCHAR(300)),4) ||  SUBSTRING(CAST(A.VDPEDIPE_NIT AS VARCHAR(300)),5,2) || SUBSTRING(CAST(VDPEDIPE_NIT AS VARCHAR(300)),7,2) AS DATE)) = YEAR(CURDATE())