SELECT A.VDCEVPEN_NRCCEV AS "NUM. CONTRATO", A.VDCEVPEN_NPED AS 'NUM. PED', A.VDCEVPEN_CODCLI AS 'COD.CLIENTE', D.VDPEDIPE_CODR AS 'PRODUTO', C.VDPRDPRD_DESCRI AS 'PRD. DESC', CAST(RIGHT(CAST(A.VDCEVPEN_DTV AS VARCHAR(300)),2) || '/' || SUBSTRING(CAST(A.VDCEVPEN_DTV AS VARCHAR(300)),5,2) || '/' || LEFT(CAST(A.VDCEVPEN_DTV AS VARCHAR(300)),4) AS VARCHAR(300)) AS 'VALIDADE',  A.VDCEVPEN_QTDPRD_ORI AS 'QUANT.'

FROM CEVPED01 AS A
INNER JOIN CADCLI01 AS B ON CAST(A.VDCEVPEN_CODCLI AS VARCHAR(300))=CAST(VDCLICLI_REGI AS VARCHAR(300)) || REPEAT('0',4-LENGTH(CAST(VDCLICLI_NUM AS VARCHAR(300)))) || CAST(VDCLICLI_NUM AS VARCHAR(300))
INNER JOIN PEDIT01 AS D ON A.VDCEVPEN_NPED=D.VDPEDIPE_NIT
INNER JOIN CADPRD01 AS C ON D.VDPEDIPE_CODR=C.VDPRDPRD_CODR

WHERE A.VDCEVPEN_DTE >= 20200101 AND A.VDCEVPEN_DTE < 20220101