SELECT DISTINCT A.VDPEDCPE_CODCLI  AS 'COD. CLIENTE', CAST(SUBSTRING(CAST(A.VDPEDCPE_NPED AS VARCHAR(300)),9,5) AS VARCHAR(300)) AS 'PEDIDO',   

CASE
      WHEN B.VDPEDIPE_CODR = 2494 THEN B.VDPEDIPE_QTDPRD
   END AS '600ML',

   CASE
      WHEN B.VDPEDIPE_CODR = 152594 THEN B.VDPEDIPE_QTDPRD
   END AS '300ML',

   CASE
      WHEN B.VDPEDIPE_CODR = 107381 THEN B.VDPEDIPE_QTDPRD
   END AS '1L',


CASE
         WHEN B.VDPEDIPE_CODR = 100559 
         OR 
         B.VDPEDIPE_CODR = 100579 
         OR 
         B.VDPEDIPE_CODR = 171690 
         
         THEN B.VDPEDIPE_QTDPRD
   END AS 'REFR. PEQ',

CASE
         WHEN B.VDPEDIPE_CODR = 198579 
         OR 
         B.VDPEDIPE_CODR = 50473 
         OR 
         B.VDPEDIPE_CODR = 50475 
         OR 
         B.VDPEDIPE_CODR = 171620 
         OR 
         B.VDPEDIPE_CODR = 99900018 
         OR 
         B.VDPEDIPE_CODR = 197061 
         OR 
         B.VDPEDIPE_CODR = 197196 
         OR 
         B.VDPEDIPE_CODR = 33422 
         
         THEN B.VDPEDIPE_QTDPRD
   END AS 'REFR. GRD',

   CASE
      WHEN B.VDPEDIPE_CODR = 128425 THEN B.VDPEDIPE_QTDPRD
   END AS 'MESA PLAS'


FROM PEDCP02 AS A
INNER JOIN PEDIT02 AS B ON A.VDPEDCPE_NPED=B.VDPEDIPE_NIT

WHERE CAST(LEFT(CAST(VDPEDCPE_NPED AS VARCHAR(300)),4) || SUBSTRING(CAST(VDPEDCPE_NPED AS VARCHAR(300)),5,2) || SUBSTRING(CAST(VDPEDCPE_NPED AS VARCHAR(300)),7,2) AS DATE) = CURDATE() - 1 AND A.VDPEDCPE_CANCHR = 0