SELECT A.CRMOVMOV_CCLI as 'COD. CLIENTE', 

CAST(LEFT(CAST(A.CRMOVMOV_DTE AS VARCHAR(300)),4) || SUBSTRING(CAST(A.CRMOVMOV_DTE AS VARCHAR(300)),5,2) || RIGHT(CAST(A.CRMOVMOV_DTE AS VARCHAR(300)),2) AS DATE)
 AS 'DATA DE EMISSAO', 
 
 CAST(LEFT(CAST(A.CRMOVMOV_DTV AS VARCHAR(300)),4) || SUBSTRING(CAST(A.CRMOVMOV_DTV AS VARCHAR(300)),5,2) || RIGHT(CAST(A.CRMOVMOV_DTV AS VARCHAR(300)),2) AS DATE)
 AS 'DATA DE VENCIMENTO', 
 
 A.CRMOVMOV_VALOR AS "VLR DO TITULO"

FROM CADMOV01 AS A