SELECT DISTINCT A.VDPEDCPE_CODCLI  AS 'COD. CLIENTE', CAST(SUBSTRING(CAST(A.VDPEDCPE_NPED AS VARCHAR(300)),9,5) AS VARCHAR(300)) AS 'PEDIDO',   
   
   CASE
      WHEN F.VDPEDIPE_CODR = 901133 THEN F.VDPEDIPE_QTDPRD
   END AS '901133',

   CASE
      WHEN F.VDPEDIPE_CODR = 902311 THEN F.VDPEDIPE_QTDPRD
   END AS '902311',

   CASE
      WHEN F.VDPEDIPE_CODR = 903061 THEN F.VDPEDIPE_QTDPRD
   END AS '903061',

   CASE
      WHEN F.VDPEDIPE_CODR = 903129 THEN F.VDPEDIPE_QTDPRD
   END AS '903129',

   CASE
      WHEN F.VDPEDIPE_CODR = 902402 THEN F.VDPEDIPE_QTDPRD
   END AS '902402',

   CASE
      WHEN F.VDPEDIPE_CODR = 904213 THEN F.VDPEDIPE_QTDPRD
   END AS '904213',

   CASE
      WHEN F.VDPEDIPE_CODR = 2494 THEN F.VDPEDIPE_QTDPRD
   END AS '600ML',

   CASE
      WHEN F.VDPEDIPE_CODR = 152594 THEN F.VDPEDIPE_QTDPRD
   END AS '300ML',

   CASE
      WHEN F.VDPEDIPE_CODR = 107381 THEN F.VDPEDIPE_QTDPRD
   END AS '1L',


   SUM(
      CASE
         WHEN F.VDPEDIPE_CODR = 100559 
         OR 
         F.VDPEDIPE_CODR = 100579 
         OR 
         F.VDPEDIPE_CODR = 171690 
         
         THEN F.VDPEDIPE_QTDPRD
   END) AS 'REFR. PEQ',

      SUM(
      CASE
         WHEN F.VDPEDIPE_CODR = 198579 
         OR 
         F.VDPEDIPE_CODR = 50473 
         OR 
         F.VDPEDIPE_CODR = 50475 
         OR 
         F.VDPEDIPE_CODR = 171620 
         OR 
         F.VDPEDIPE_CODR = 99900018 
         OR 
         F.VDPEDIPE_CODR = 197061 
         OR 
         F.VDPEDIPE_CODR = 197196 
         OR 
         F.VDPEDIPE_CODR = 33422 
         
         THEN F.VDPEDIPE_QTDPRD
   END) AS 'REFR. GRD',

   CASE
      WHEN F.VDPEDIPE_CODR = 128425 THEN F.VDPEDIPE_QTDPRD
   END AS 'MESA PLAS.'


FROM PEDCP01 AS A
INNER JOIN CADCLI01 AS B ON CAST(A.VDPEDCPE_CODCLI AS VARCHAR(300))=CAST(VDCLICLI_REGI AS VARCHAR(300)) || REPEAT('0',4-LENGTH(CAST(VDCLICLI_NUM AS VARCHAR(300)))) || CAST(VDCLICLI_NUM AS VARCHAR(300))
INNER JOIN CADVEN01 AS D ON A.VDPEDCPE_VEN_ORI_CLI=D.VDVENVEN_CODMOV
INNER JOIN CONDPG01 AS E ON A.VDPEDCPE_CPG=E.VDCADPAG_COD
INNER JOIN PEDIT01 AS F ON A.VDPEDCPE_NPED=F.VDPEDIPE_NIT

WHERE CAST(LEFT(CAST(VDPEDCPE_NPED AS VARCHAR(300)),4) || SUBSTRING(CAST(VDPEDCPE_NPED AS VARCHAR(300)),5,2) || SUBSTRING(CAST(VDPEDCPE_NPED AS VARCHAR(300)),7,2) AS DATE) = CURDATE() - 4 AND A.VDPEDCPE_CANCHR = 0

GROUP BY A.VDPEDCPE_CODCLI, A.VDPEDCPE_NPED, F.VDPEDIPE_CODR, F.VDPEDIPE_QTDPRD